# -*- coding: utf-8 -*-
"""HaticeBIYIK_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9-ddZFaOlHflePIayZ6i6WGgOk-TaVG
"""

import random
list=[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79]
m1=[[0 for x in range(3)] for y in range(3)]
for i in range(3): 
  for j in range(3): 
    m1[i][j]=random.choice(list)
print(m1)